services:
  symptom-checker:
    build: ./services/symptom-checker-service
    ports:
      - "5005:5005"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MONGO_URI=mongodb://mongodb-ai:27017/symptom_db
      - PATIENT_SERVICE_URL=http://patient-service:5002
    depends_on:
      - mongodb-ai
      - patient-service
    networks:
      - medizen-network

  mongodb-ai: 
    image: mongo:latest
    container_name: mongodb-ai
    ports:
      - "27017:27017"
    volumes:
      - symptom-data:/data/db
    networks:
      - medizen-network

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - medizen-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - medizen-network

networks:
  medizen-network:
    driver: bridge

volumes:
<<<<<<< Updated upstream
  symptom-data:
=======
  mongo-db-data:
  mongodb-data:
  symptom-data:
  grafana-storage:
>>>>>>> Stashed changes
