services:
  symptom-checker:
    build: ./services/symptom-checker-service
    ports:
      - "5005:5005"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MONGO_URI=mongodb://mongodb-ai:27017/symptom_db
    depends_on:
      - mongodb-ai
    networks:
      - medizen-network

  mongodb-ai: 
    image: mongo:latest
    container_name: mongodb-ai
    ports:
      - "27017:27017"
    volumes:
      - symptom-data:/data/db
    networks:
      - medizen-network

networks:
  medizen-network:
    driver: bridge

volumes:
  symptom-data: