apiVersion: v1
kind: ConfigMap
metadata:
  name: medizen-config
  namespace: default
data:
  # General
  NODE_ENV: "development"

  # Port configurations
  AUTH_SERVICE_PORT: "5001"
  PATIENT_SERVICE_PORT: "5002"
  DOCTOR_SERVICE_PORT: "5003"
  APPOINTMENT_SERVICE_PORT: "5004"
  SYMPTOM_SERVICE_PORT: "5005"
  TELEMEDICINE_SERVICE_PORT: "5006"
  PAYMENT_SERVICE_PORT: "5007"
  NOTIFICATION_SERVICE_PORT: "5008"
  ADMIN_SERVICE_PORT: "5009"
  GATEWAY_PORT: "5010"

  # Internal Service URLs
  AUTH_SERVICE_URL: "http://auth-service:5001"
  PATIENT_SERVICE_URL: "http://patient-service:5002"
  DOCTOR_SERVICE_URL: "http://doctor-service:5003"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:5004"
  SYMPTOM_SERVICE_URL: "http://symptom-checker-service:5005"
  TELEMEDICINE_SERVICE_URL: "http://telemedicine-service:5006"
  PAYMENT_SERVICE_URL: "http://payment-service:5007"
  NOTIFICATION_SERVICE_URL: "http://notification-service:5008"
  ADMIN_SERVICE_URL: "http://admin-service:5009"
  
  # Infrastructure
  RABBITMQ_URL_INTERNAL: "amqp://rabbitmq-service:5672"
  RABBITMQ_QUEUE: "notifications_queue"
  
  # External URLs
  VITE_GATEWAY_URL: "http://api-gateway:5010"

  # Other
  VONAGE_FROM: "MediZen"
  SMTP_HOST: "smtp.mailtrap.io"
  SMTP_PORT: "587"
  SMTP_FROM: "noreply@medizen.com"
