apiVersion: v1
kind: Secret
metadata:
  name: medizen-secrets
type: Opaque
stringData:
  # To populate these, use: echo -n "value" | base64
  CLERK_SECRET_KEY: "sk_test_ezCKgN9U9W8jKMuCr2qTkhU8WQCiNQRBz5hALAlwhu"
  CLERK_PUBLISHABLE_KEY: "pk_test_YnJhdmUtdnVsdHVyZS04Ni5jbGVyay5hY2NvdW50cy5kZXYk"
  GEMINI_API_KEY: "AIzaSyDj_alHVCPC9Nsgh4etgyxx5ShgyxYpTvc"
  MONGO_URI: "mongodb+srv://savinduweerarathna_db_user:njINEB46cKEqjwUk@medizen.qb4eycl.mongodb.net/?appName=MediZen"
  DOCTOR_MONGO_URI: "mongodb+srv://savinduweerarathna_db_user:njINEB46cKEqjwUk@medizen.qb4eycl.mongodb.net/doctor_db?retryWrites=true&w=majority&appName=MediZen"
