apiVersion: v1
kind: Secret
metadata:
  name: medizen-secrets
  namespace: default
type: Opaque
stringData:
  # MongoDB URIs
  MONGO_URI: "mongodb+srv://savinduweerarathna_db_user:njINEB46cKEqjwUk@medizen.qb4eycl.mongodb.net/?appName=MediZen"
  MONGO_URI_DOCTOR: "mongodb+srv://savinduweerarathna_db_user:njINEB46cKEqjwUk@medizen.qb4eycl.mongodb.net/doctor_db?appName=MediZen"
  MONGO_URI_APPOINTMENT: "mongodb+srv://savinduweerarathna_db_user:njINEB46cKEqjwUk@medizen.qb4eycl.mongodb.net/appointment_db?appName=MediZen"
  MONGO_URI_SESSION: "mongodb+srv://savinduweerarathna_db_user:njINEB46cKEqjwUk@medizen.qb4eycl.mongodb.net/session_db?appName=MediZen"
  MONGO_URI_PAYMENT: "mongodb+srv://savinduweerarathna_db_user:njINEB46cKEqjwUk@medizen.qb4eycl.mongodb.net/payment_db?appName=MediZen"
  MONGO_URI_NOTIFICATION: "mongodb+srv://savinduweerarathna_db_user:njINEB46cKEqjwUk@medizen.qb4eycl.mongodb.net/notification_db?appName=MediZen"
  MONGO_URI_ADMIN: "mongodb+srv://savinduweerarathna_db_user:njINEB46cKEqjwUk@medizen.qb4eycl.mongodb.net/admin_db?appName=MediZen"
  MONGO_URI_SYMPTOM: "mongodb+srv://savinduweerarathna_db_user:njINEB46cKEqjwUk@medizen.qb4eycl.mongodb.net/symptom_db?appName=MediZen"

  # Clerk
  CLERK_SECRET_KEY: "sk_test_ezCKgN9U9W8jKMuCr2qTkhU8WQCiNQRBz5hALAlwhu"
  CLERK_PUBLISHABLE_KEY: "pk_test_YnJhdmUtdnVsdHVyZS04Ni5jbGVyay5hY2NvdW50cy5kZXYk"

  # JWT
  JWT_SECRET: "medizen_secret_key_2026"

  # Cloudinary
  CLOUDINARY_CLOUD_NAME: "dncrmo2ch"
  CLOUDINARY_API_KEY: "179732894546456"
  CLOUDINARY_API_SECRET: "wJHY0_FdZQB6cdxGyN9oKf_PxyY"

  # Vonage / SMS
  VONAGE_API_KEY: "your_vonage_api_key_here"
  VONAGE_API_SECRET: "your_vonage_api_secret_here"

  # SMTP
  SMTP_USER: "your_smtp_user_here"
  SMTP_PASS: "your_smtp_pass_here"

  # Stripe
  STRIPE_SECRET_KEY: "your_stripe_secret_key_here"
  STRIPE_WEBHOOK_SECRET: "your_stripe_webhook_secret_here"

  # AI
  GEMINI_API_KEY: "AIzaSyCaaH9-27j25dMydCgZEQfOs3meKdfewh8"

  # Agora
  AGORA_APP_ID: "your_agora_app_id_here"
  AGORA_APP_CERTIFICATE: "your_agora_app_certificate_here"

  # RabbitMQ
  RABBITMQ_URL: "amqp://rabbitmq-service:5672"
