apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - name: admin-service
        image: savindus/medizen-admin-service:latest
        ports:
        - containerPort: 5009
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: medizen-secrets
              key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 5009
      targetPort: 5009
  type: ClusterIP
