apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: savindus/medizen-appointment-service:latest
        ports:
        - containerPort: 5004
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: medizen-secrets
              key: MONGO_URI
        envFrom:
        - configMapRef:
            name: appointment-config

---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  selector:
    app: appointment-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: ClusterIP