apiVersion: v1
kind: ConfigMap
metadata:
  name: doctor-config
data:
  PORT: "5003"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: appointment-config
data:
  PORT: "5004"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telemedicine-config
data:
  PORT: "5006"
