apiVersion: v1
kind: ConfigMap
metadata:
  name: medizen-config
  namespace: default
data:
  # Admin Service
  ADMIN_SERVICE_PORT: "5009"
  AUTH_SERVICE_URL: "http://auth-service:5001/api/auth"

  # Payment Service
  PAYMENT_SERVICE_PORT: "5007"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:5004/api/appointments"

  # Notification Service
  NOTIFICATION_SERVICE_PORT: "5008"
  EMAIL_USER: "medizen.system@example.com"
  TWILIO_SID: "YOUR_TWILIO_SID"
  TWILIO_PHONE_NUMBER: "YOUR_TWILIO_PHONE_NUMBER"
  RABBITMQ_URL: "amqp://rabbitmq-service:5672"

---
apiVersion: v1
kind: Secret
metadata:
  name: medizen-secrets
  namespace: default
type: Opaque
stringData:
  # Common
  MONGO_URI: "YOUR_MONGO_URI"
  JWT_SECRET: "YOUR_JWT_SECRET"

  # Payment specific
  STRIPE_SECRET_KEY: "YOUR_STRIPE_SECRET_KEY"
  STRIPE_WEBHOOK_SECRET: "YOUR_STRIPE_WEBHOOK_SECRET"

  # Notification specific
  EMAIL_PASS: "YOUR_EMAIL_APP_PASSWORD"
  TWILIO_AUTH_TOKEN: "YOUR_TWILIO_AUTH_TOKEN"