apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: savindus/medizen-api-gateway:latest
          ports:
            - containerPort: 5010
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:5001"
            - name: PATIENT_SERVICE_URL
              value: "http://patient-service:5002"
            - name: DOCTOR_SERVICE_URL
              value: "http://doctor-service:5003"
            - name: APPOINTMENT_SERVICE_URL
              value: "http://appointment-service:5004"
            - name: SYMPTOM_SERVICE_URL
              value: "http://symptom-checker-service:5005"
            - name: TELEMEDICINE_SERVICE_URL
              value: "http://telemedicine-service:5006"
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service:5007"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://notification-service:5008"
            - name: ADMIN_SERVICE_URL
              value: "http://admin-service:5009"

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5010
