apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: savindus/medizen-api-gateway:latest
        ports:
        - containerPort: 5010
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: GATEWAY_PORT
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: AUTH_SERVICE_URL
        - name: PATIENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: PATIENT_SERVICE_URL
        - name: DOCTOR_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: DOCTOR_SERVICE_URL
        - name: APPOINTMENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: APPOINTMENT_SERVICE_URL
        - name: SYMPTOM_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: SYMPTOM_SERVICE_URL
        - name: TELEMEDICINE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: TELEMEDICINE_SERVICE_URL
        - name: PAYMENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: PAYMENT_SERVICE_URL
        - name: NOTIFICATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: NOTIFICATION_SERVICE_URL
        - name: ADMIN_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: ADMIN_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 5010
      targetPort: 5010
  type: LoadBalancer
