apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: savindus/medizen-client:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_CLERK_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: medizen-secrets
              key: CLERK_PUBLISHABLE_KEY
        - name: VITE_GATEWAY_URL
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: VITE_GATEWAY_URL
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
