apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name: patient-service
          image: savindus/medizen-patient-service:latest
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: medizen-config
                  key: PATIENT_SERVICE_PORT
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: medizen-secrets
                  key: MONGO_URI
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: medizen-secrets
                  key: CLERK_SECRET_KEY
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: medizen-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: medizen-secrets
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: medizen-secrets
                  key: CLOUDINARY_API_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  selector:
    app: patient-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
