apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
      - name: payment-service
        image: savindus/medizen-payment-service:latest
        ports:
        - containerPort: 5007
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: PAYMENT_SERVICE_PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: NODE_ENV
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: medizen-secrets
              key: MONGO_URI_PAYMENT
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: medizen-secrets
              key: STRIPE_SECRET_KEY
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: medizen-secrets
              key: STRIPE_WEBHOOK_SECRET
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: medizen-secrets
              key: RABBITMQ_URL
        - name: RABBITMQ_QUEUE
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: RABBITMQ_QUEUE
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 5007
      targetPort: 5007
  type: ClusterIP
