apiVersion: apps/v1
kind: Deployment
metadata:
  name: symptom-checker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symptom-checker-service
  template:
    metadata:
      labels:
        app: symptom-checker-service
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
      - name: symptom-checker-service
        image: savindus/medizen-symptom-checker-service:latest
        ports:
        - containerPort: 5005
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: SYMPTOM_SERVICE_PORT
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: medizen-secrets
              key: GEMINI_API_KEY
        - name: PATIENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: PATIENT_SERVICE_URL
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: medizen-secrets
              key: MONGO_URI_SYMPTOM
---
apiVersion: v1
kind: Service
metadata:
  name: symptom-checker-service
spec:
  selector:
    app: symptom-checker-service
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
  type: ClusterIP
