apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
      - name: telemedicine-service
        image: savindus/medizen-telemedicine-service:latest
        ports:
        - containerPort: 5006
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: TELEMEDICINE_SERVICE_PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: medizen-config
              key: NODE_ENV
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: medizen-secrets
              key: MONGO_URI_SESSION
        - name: AGORA_APP_ID
          valueFrom:
            secretKeyRef:
              name: medizen-secrets
              key: AGORA_APP_ID
        - name: AGORA_APP_CERTIFICATE
          valueFrom:
            secretKeyRef:
              name: medizen-secrets
              key: AGORA_APP_CERTIFICATE
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: medizen-secrets
              key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: telemedicine-service
spec:
  selector:
    app: telemedicine-service
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 5006
  type: ClusterIP
