name: Appointment Service CI/CD

on:
  push:
    branches: ["main", "Doctor-service", "clinical-consultation-suite"]
    paths:
      - "services/appointment-service/**"
  pull_request:
    branches: ["main"]
    paths:
      - "services/appointment-service/**"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "services/appointment-service/package-lock.json"

      - name: Install dependencies
        run: |
          cd services/appointment-service
          npm install

      - name: Source Code Verification
        run: |
          cd services/appointment-service
          node --check src/index.js

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Appointment Service
        uses: docker/build-push-action@v5
        with:
          context: ./services/appointment-service
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/medizen-appointment-service:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/medizen-appointment-service:${{ github.sha }}

      - name: Set K8s Context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to K8s
        uses: azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            k8s/appointment-k8s.yaml
            k8s/medizen-config-secrets.yaml
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/medizen-appointment-service:${{ github.sha }}
